[[plugins]] # Dark powered Vim/Neovim plugin manager
repo = 'Shougo/dein.vim'

# [[plugins]] # Interactive command execution in Vim.
# repo = 'Shougo/vimproc.vim'
# build = 'make'
# hook_post_update = '''
#   if dein#util#_is_windows()
#     let cmd = 'tools\\update-dll-mingw'
#   elseif dein#util#_is_cygwin()
#     let cmd = 'make -f make_cygwin.mak'
#   elseif dein#util#_is_mac()
#     let cmd = 'make -f make_mac.mak'
#   elseif executable('gmake')
#     let cmd = 'gmake'
#   else
#     let cmd = 'make'
#   endif
#   let g:dein#plugin.build = cmd
# '''

[[plugins]] # Powerful file explorer implemented by Vim script
repo = 'Shougo/vimfiler.vim'
depends = ['unite.vim']

[[plugins]] # fugitive.vim: a Git wrapper so awesome, it should be illegal
repo = 'tpope/vim-fugitive'

# Asynchronously control git repositories in Neovim/Vim 8
[[plugins]]
repo = 'lambdalisue/gina.vim'

[[plugins]]
repo = 'cohama/agit.vim'

[[plugins]]
repo = 'lambdalisue/vim-gita'

[[plugins]]
repo = 'mattn/webapi-vim'

[[plugins]] # rails.vim: Ruby on Rails power tools
repo = 'tpope/vim-rails'

# [[plugins]] # Run Rspec specs from Vim
# repo = 'thoughtbot/vim-rspec'

[[plugins]] # This is a Rspec runner for Vim.
repo = 'taichouchou2/neorspec.vim'

[[plugins]] # emmet for vim: http://emmet.io/
repo = 'mattn/emmet-vim'

[[plugins]]
repo = 'osyo-manga/vim-monster'

[[plugins]] # dispatch.vim: asynchronous build and test dispatcher
repo = 'tpope/vim-dispatch'

#-------------------------------------------------------------------------------
# Unite
#-------------------------------------------------------------------------------
# Unite and create user interfaces
[[plugins]]
repo = 'Shougo/unite.vim'

# outline source for unite.vim
[[plugins]]
repo = 'Shougo/unite-outline'

# tags soruce for unite.vim
[[plugins]]
repo = 'tsukkee/unite-tag'

[[plugins]]
repo = 'osyo-manga/unite-quickfix'

[[plugins]] # A unite.vim plugin
repo = 'ujihisa/unite-colorscheme'

[[plugins]] # Unite source for git conflicts.
repo = 'moznion/unite-git-conflict.vim'

[[plugins]] #  vim-unite-watson.vim is the unite source for watson.
repo   = 'alpaca-tc/vim-unite-watson.vim'
on_cmd = 'Watson'

[[plugins]] # a unite.vim plugin for rails
repo = 'basyura/unite-rails'

[[plugins]]
repo = 'iyuuya/unite-rails-fat'

[[plugins]]
repo = 'iyuuya/unite-rails-serializer'

[[plugins]]
repo = 'tsukkee/unite-help'

# [[plugins]]
# repo = 'iyuuya/unite-ale'
# depends = ['unite.vim', 'ale']

[[plugins]]
repo = 'Shougo/denite.nvim'

[[plugins]]
repo = 'iyuuya/denite-rails'

[[plugins]]
repo = 'iyuuya/denite-ale'

#-------------------------------------------------------------------------------
# ColorScheme
#-------------------------------------------------------------------------------
[[plugins]] # A dark colour scheme for Vim & gVim
repo = 'w0ng/vim-hybrid'
on_cmd = 'colorscheme'

[[plugins]] # A colorful, dark color scheme for Vim.
repo = 'nanotech/jellybeans.vim'
on_cmd = 'colorscheme'

[[plugins]] # Molokai color scheme for Vim
repo = 'tomasr/molokai'
on_cmd = 'colorscheme'

[[plugins]] # Tomorrow Theme for Vim
repo = 'chriskempson/vim-tomorrow-theme'
on_cmd = 'colorscheme'

[[plugins]] # Wombat for 256 color xterms
repo = 'vim-scripts/wombat256.vim'
on_cmd = 'colorscheme'

[[plugins]] # Dark blue color scheme for Vim
repo = 'cocopon/iceberg.vim'
on_cmd = 'colorscheme'

#-------------------------------------------------------------------------------
# TODO: 整理すること
#-------------------------------------------------------------------------------
[[plugins]] # A Vim plugin which shows a git diff in the gutter (sign column) and stages/reverts hunks.
repo = 'airblade/vim-gitgutter'

[[plugins]] # repeat.vim: enable repeating supported plugin maps with '.'
repo = 'tpope/vim-repeat'

[[plugins]] # abolish.vim: easily search for, substitute, and abbreviate multiple variants of a word
repo = 'tpope/vim-abolish'

[[plugins]]
repo = 'thinca/vim-template'

[[plugins]]
repo = 'vim-scripts/dbext.vim'

[[plugins]]
repo = 'tyru/open-browser.vim'

[[plugins]] # Open GitHub URL of current file, etc. from Vim editor (supported GitHub Enterprise)
repo = 'tyru/open-browser-github.vim'
depends = 'open-browser.vim'

[[plugins]] # Integrated reference viewer.
repo = 'thinca/vim-ref'

[[plugins]]
repo = 'lambdalisue/vim-gista'

[[plugins]] # Run commands quickly.
repo = 'thinca/vim-quickrun'
depends = 'quickrunex-vim'

[[plugins]] # Async syntax checking.
repo = 'osyo-manga/vim-watchdogs'

[[plugins]]
repo = 'osyo-manga/shabadou.vim'

# [[plugins]] # Syntax checking hacks for vim
# repo = 'scrooloose/syntastic'

[[plugins]] # Highlight quickfix errors
repo = 'jceb/vim-hier'

[[plugins]] # See quickfix, location list and Syntastic lists errors and warnings as you move through a vim file.
repo = 'dannyob/quickfixstatus'

[[plugins]]
repo = 'w0rp/ale'

[[plugins]]
repo = 'vim-scripts/AnsiEsc.vim'

[[plugins]]
repo = 'osyo-manga/vim-over'

[[plugins]] # surround.vim: quoting/parenthesizing made simple
repo = 'tpope/vim-surround'

[[plugins]] # emmet for vim: http://emmet.io/
repo = 'mattn/emmet-vim'

[[plugins]] # The Vim RuboCop plugin runs RuboCop and displays the results in Vim
repo = 'ngmy/vim-rubocop'

[[plugins]] # sophisticated comment plugin http://www.vim.org/scripts/script.php?script_id=2554
repo = 'tyru/caw.vim'

[[plugins]]
repo = 'basyura/twibill.vim'

[[plugins]]
repo = 'basyura/bitly.vim'

# [[plugins]]
# repo = 'mattn/favstar-vim'

# [[plugins]]
# repo = 'basyura/TweetVim'
# depends = ['open-browser.vim', 'twibill.vim', 'bitly.vim', 'webapi-vim', 'favstar-vim']

# [[plugins]]
# repo = 'basyura/J6uil.vim'

[[plugins]]
repo = 'vim-jp/vital.vim'

[[plugins]]
repo = '5t111111/alt-gtags.vim'

[[plugins]]
repo = 'szw/vim-tags'

[[plugins]]
repo = 'editorconfig/editorconfig-vim'

[[plugins]]
repo = 'AndrewRadev/switch.vim'

[[plugins]]
repo = 'mattn/httpstatus-vim'

# [[plugins]]
# repo = 'itchyny/lightline.vim'

# [[plugins]]
# repo = 'Shougo/context_filetype.vim'
# 
# [[plugins]]
# repo = 'osyo-manga/vim-precious'

[[plugins]]
repo = 'junegunn/fzf'
build = './install --all'
merged = 0

[[plugins]]
repo = 'junegunn/fzf.vim'
depends = ['fzf']

# neo-snippet plugin contains neocomplcache snippets source
[[plugins]]
repo  = 'Shougo/neosnippet.vim'
depends = 'neosnippet-snippets'

# The standard snippets repository for neosnippet
[[plugins]]
repo = 'Shougo/neosnippet-snippets'

# Vim plugin: Create your own text object
[[plugins]]
repo = 'kana/vim-textobj-user'

# Make text objects with various ruby block structures.
[[plugins]]
repo = 'rhysd/vim-textobj-ruby'

[[plugins]] # very simple vim plugin for easy resizing of your vim windows
repo = 'simeji/winresizer'

[[plugins]] # Wrapper of some neovim's :terminal functions.
repo = 'kassio/neoterm'
