[[plugins]]
repo    = 'Shougo/neomru.vim'
on_path = '.*'

[[plugins]]
repo    = 'Shougo/neoyank.vim'
on_path = '.*'
on_i    = 1

# Powerful shell implemented by vim.
#[[plugins]]
#repo = 'Shougo/vimshell.vim'

# Dark powered asynchronous completion framework for neovim
[[plugins]]
repo = 'Shougo/deoplete.nvim'
on_i = 1

[[plugins]]
repo    = 'landaire/deoplete-swift'
on_ft   = 'swift'
depends = 'deoplete.nvim'

# the world first vimshell plugin that you can run 'vim' command on ssh on vimshell
#[[plugins]]
#repo    = 'ujihisa/vimshell-ssh'
#depends = 'vimshell.vim'

[[plugins]] # endwise.vim: wisely add 'end' in ruby, endfunction/endif/more in vim script, etc
repo = 'alpaca-tc/vim-endwise'
on_i = 1

[[plugins]] # Vim plugin for the_silver_searcher, 'ag', a replacement for the Perl module / CLI script 'ack'
repo   = 'rking/ag.vim'
on_cmd = 'Ag'

[[plugins]]
repo   = 'thinca/vim-scouter'
on_cmd = 'Scouter'

[[plugins]] # Async clang code completion.
repo = 'osyo-manga/vim-marching'
on_ft = ['c', 'cpp']

[[plugins]] # Align Them All!
repo = 'h1mesuke/vim-alignta'
on_cmd = ['Align', 'Alignta']

[[plugins]] # eskk aims to provide powerful input method platform in Vim.
repo = 'tyru/eskk.vim'
on_i = 1

[[plugins]] # Realtime preview by Vim. (Markdown, reStructuredText, textile)
repo = 'kannokanno/previm'
on_ft = 'markdown'
on_cmd = 'PrevimOpen'

#-------------------------------------------------------------------------------
# FileType/Syntax
#-------------------------------------------------------------------------------
[[plugins]] # Vim syntax for TOML
repo  = 'cespare/vim-toml'
on_ft = 'toml'

[[plugins]] # (Soon to be) the official repository for the AsciiDoc syntax support in VIM
repo  = 'asciidoc/vim-asciidoc' 
on_ft = 'asciidoc'

[[plugins]] # Textile for VIM
repo  = 'timcharper/textile.vim' 
on_ft = 'textile'

# vim syntax file for plantuml
repo  = 'aklt/plantuml-syntax'
on_ft = 'plantuml'

[[plugins]]
repo  = 'kchmck/vim-coffee-script'
on_ft = 'coffee'

[[plugins]]
repo  = 'slim-template/vim-slim'
on_ft = 'slim'

[[plugins]]
repo  = 'vim-jp/cpp-vim'
on_ft = 'cpp'

[[plugins]]
repo  = 'chase/vim-ansible-yaml'
on_ft = ['yaml', 'ansible']

[[plugins]]
repo  = 'kylef/apiblueprint.vim'
on_ft = 'apiblueprint'

[[plugins]]
repo  = 'leafgarland/typescript-vim'
on_ft = 'typescript'

[[plugins]]
repo  = 'lmeijvogel/vim-yaml-helper'
on_ft = ['yaml', 'ansible']

[[plugins]]
repo  = 'fatih/vim-go'
on_ft = 'go'

[[plugins]] # Vim support for editing fish scripts
repo  = 'dag/vim-fish'
on_ft = 'fish'

[[plugins]]
repo  = 'jvirtanen/vim-octave'
on_ft = 'octave'

[[plugins]]
repo  = 'elixir-lang/vim-elixir'
on_ft = 'elixir'

[[plugins]]
repo  = 'mattreduce/vim-mix'
on_ft = 'elixir'

[[plugins]]
repo  = 'BjRo/vim-extest'
on_ft = 'elixir'

[[plugins]]
repo  = 'kbrw/elixir.nvim'
on_ft = 'elixir'
build = './install.sh'

[[plugins]]
repo  = 'avdgaag/vim-phoenix'
on_ft = 'elixir'

[[plugins]]
repo  = 'kballard/vim-swift'
on_ft = 'swift'

[[plugins]]
repo  = 'keith/swift.vim'
on_ft = 'swift'

# Vastly improved Javascript indentation and syntax support in Vim.
[[plugins]]
repo = 'pangloss/vim-javascript'
on_ft = ['javascript', 'javascript.jsx']

# YAJS.vim: Yet Another JavaScript Syntax for Vim
# [[plugins]]
# repo = 'othree/yajs.vim'
# on_ft = ['javascript', 'javascript.jsx']

# Syntax for JavaScript libraries
[[plguins]]
repo = 'othree/javascript-libraries-syntax.vim'
on_ft = ['javascript', 'javascript.jsx']

# ES.Next syntax for Vim
[[plugins]]
repo = 'othree/es.next.syntax.vim'
on_ft = ['javascript', 'javascript.jsx']

# [[plugins]]
repo = 'mxw/vim-jsx'
on_ft = ['javascript', 'javascript.jsx']

# [Vim script] React JSX syntax pretty highlighting for vim.
# [[plugins]]
# repo = 'maxmellon/vim-jsx-pretty'
# on_ft = ['javascript', 'javascript.jsx']

# Tern plugin for Vim
[[plugins]]
repo = 'ternjs/tern_for_vim'
build = 'npm install'
on_ft = ['javascript', 'javascript.jsx']

[[plugins]]
repo  = 'chr4/nginx.vim'
on_ft = 'nginx'
