# "NeoBundle 'airblade/vim-gitgutter' " A Vim plugin which shows a git diff in the gutter (sign column) and stages/reverts hunks.
# "NeoBundle 'tpope/vim-repeat'           " repeat.vim: enable repeating supported plugin maps with '.'
# "NeoBundle 'tpope/vim-abolish'          " abolish.vim: easily search for, substitute, and abbreviate multiple variants of a word
# " A git repository for a vim plugin called matchit
# NeoBundleLazy 'edsono/vim-matchit', { 'autoload' : {
#       \ 'filetypes' : 'ruby',
#       \ 'mappings' : [',nx', '%'] } }
# NeoBundle 'thinca/vim-template'
# NeoBundle 'kannokanno/previm' " Realtime preview by Vim. (Markdown, reStructuredText, textile)
# NeoBundle 'vim-scripts/dbext.vim'
# NeoBundle 'tyru/open-browser.vim'
# NeoBundle 'thinca/vim-ref' " Integrated reference viewer.
# NeoBundle 'lambdalisue/vim-gista'
# NeoBundle 'thinca/vim-quickrun', { 'depends' : 'mattn/quickrunex-vim' } " Run commands quickly.
# NeoBundle 'osyo-manga/vim-watchdogs' " Async syntax checking.
# NeoBundle 'osyo-manga/shabadou.vim'
# NeoBundle 'scrooloose/syntastic' " Syntax checking hacks for vim
# NeoBundle 'jceb/vim-hier' " Highlight quickfix errors
# NeoBundle 'dannyob/quickfixstatus' " See quickfix, location list and Syntastic lists errors and warnings as you move through a vim file.
# NeoBundle 'vim-scripts/AnsiEsc.vim'
# NeoBundle 'osyo-manga/vim-over'
# NeoBundle 'tpope/vim-surround' " surround.vim: quoting/parenthesizing made simple
# NeoBundle 'mattn/emmet-vim' " emmet for vim: http://emmet.io/
# NeoBundle 'ngmy/vim-rubocop' " The Vim RuboCop plugin runs RuboCop and displays the results in Vim
# NeoBundleLazy 'vim-jp/cpp-vim', {
#             \ 'autoload' : {'filetypes' : 'cpp'}
#             \ }
# NeoBundle 'osyo-manga/vim-marching', { 'autoload' : { 'filetypes' : ['c', 'cpp'] } } " Async clang code completion.
# NeoBundle 'tyru/caw.vim' " sophisticated comment plugin http://www.vim.org/scripts/script.php?script_id=2554
# 
# "NeoBundle 'basyura/TweetVim', { 'depends' : ['tyru/open-browser.vim', 'basyura/twibill.vim', 'mattn/webapi-vim', 'basyura/bitly.vim', 'mattn/favstar-vim'] }
# "NeoBundle 'basyura/J6uil.vim'
# NeoBundle 'vim-jp/vital.vim'
# "NeoBundle '5t111111/alt-gtags.vim'
# "NeoBundle 'szw/vim-tags'
# " vim: fdm=marker ft=vim
